### ISSUE TITLE
[Feature request] Have the scrolling list element resize along with full window

### ISSUE THREAD

**Issue by favna** [RainThunder/Fire-Emblem-Fates-Convoy-Editor#1]
Like the title pretty much says. I looked at the source code myself but alas I cannot determine where the scrolling list of elements is defined so I wasn't able to find it myself. To visually show what I mean the following image, the request is that the list element would in this case be equally big as the window. This is just for easier viewing.

![2016-03-14_11-54-01](https://cloud.githubusercontent.com/assets/4019718/13742580/cf420ba8-e9dc-11e5-8f1d-3e6c8001d90f.png)

**Comment by RainThunder** [comment]
Fixed in the latest commit.
