### ISSUE TITLE
[Major bug] Importing edited save wipes all 'my castle' data

### ISSUE THREAD

**Issue by favna** [RainThunder/Fire-Emblem-Fates-Convoy-Editor#2]
After using the editor my friend and I have noticed that when importing a save that hasn't been decompressed and recompressed by FEAST will wipe all 'my castle' progress. With that I mean all buildings have to be re-build and re-upgraded as well as all info on 'my card', the castle addresses has to be re-obtained, the materials are all set to 0, and so on and so forth. I will test the result of importing when using FEAST in not too long when I get home and report back, but at the least there has to be some check that confirms if the save was decompressed prior before we start editing.

**Comment by favna** [comment]
Okkaay... well up

UPDATE: When using FEAST to decompress the save, then make edits and then use FEAST again to compress it the game crashes upon loading the save and forces a reboot of the system.

**Comment by RainThunder** [comment]
Just a note: There's no need to recompress after editing.

According to [our discussion on reddit](https://www.reddit.com/r/3dshacks/comments/4ajyv8/fire_emblem_fate_convoy_editor/d11qoe1), you don't have the old save file, so this issue cannot be solved yet.
